<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-19T06:14:44 IST" name="SubmitOrderSuite" finished-at="2025-03-19T06:15:29 IST" duration-ms="44514">
    <groups>
      <group name="ErrorHandling">
        <method signature="Error_Validation_Test.login_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" name="login_error_Validation" class="com.test.Error_Validation_Test"/>
        <method signature="Error_Validation_Test.product_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" name="product_error_Validation" class="com.test.Error_Validation_Test"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2025-03-19T06:14:44 IST" name="SubmitOrderTest" finished-at="2025-03-19T06:14:59 IST" duration-ms="14086">
      <class name="com.test.SubmitOrderTest_Browser">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.SubmitOrderTest_Browser@1a6d8329]" started-at="2025-03-19T06:14:44 IST" name="launchApplication" finished-at="2025-03-19T06:14:51 IST" duration-ms="6343" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrderTest()[pri:0, instance:com.test.SubmitOrderTest_Browser@1a6d8329]" started-at="2025-03-19T06:14:51 IST" name="submitOrderTest" finished-at="2025-03-19T06:14:58 IST" duration-ms="7630" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.SubmitOrderTest_Browser@1a6d8329]" started-at="2025-03-19T06:14:58 IST" name="teardown" finished-at="2025-03-19T06:14:59 IST" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.test.SubmitOrderTest_Browser -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2025-03-19T06:14:44 IST" name="ErrorValidationTest" finished-at="2025-03-19T06:15:29 IST" duration-ms="44514">
      <class name="com.test.Error_Validation_Test">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" started-at="2025-03-19T06:14:44 IST" name="launchApplication" finished-at="2025-03-19T06:14:53 IST" duration-ms="8998" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="login_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" started-at="2025-03-19T06:14:53 IST" name="login_error_Validation" finished-at="2025-03-19T06:14:55 IST" duration-ms="1850" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.test.Error_Validation_Test.login_error_Validation(Error_Validation_Test.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_error_Validation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" started-at="2025-03-19T06:14:55 IST" name="teardown" finished-at="2025-03-19T06:14:55 IST" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" started-at="2025-03-19T06:14:55 IST" name="launchApplication" finished-at="2025-03-19T06:15:22 IST" duration-ms="26374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="product_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" started-at="2025-03-19T06:15:22 IST" name="product_error_Validation" finished-at="2025-03-19T06:15:29 IST" duration-ms="7095" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- product_error_Validation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.Error_Validation_Test@5524cca1]" started-at="2025-03-19T06:15:29 IST" name="teardown" finished-at="2025-03-19T06:15:29 IST" duration-ms="63" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.test.Error_Validation_Test -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- SubmitOrderSuite -->
</testng-results>
