<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-07T00:11:58 IST" name="SubmitOrderSuite" finished-at="2025-03-07T00:12:38 IST" duration-ms="39632">
    <groups>
    </groups>
    <test started-at="2025-03-07T00:11:58 IST" name="SubmitOrderTest" finished-at="2025-03-07T00:12:17 IST" duration-ms="18243">
      <class name="com.test.SubmitOrderTest_Browser">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.SubmitOrderTest_Browser@b7c4869]" started-at="2025-03-07T00:11:58 IST" name="launchApplication" finished-at="2025-03-07T00:12:08 IST" duration-ms="9800" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrderTest()[pri:0, instance:com.test.SubmitOrderTest_Browser@b7c4869]" started-at="2025-03-07T00:12:08 IST" name="submitOrderTest" finished-at="2025-03-07T00:12:16 IST" duration-ms="8262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.SubmitOrderTest_Browser@b7c4869]" started-at="2025-03-07T00:12:16 IST" name="teardown" finished-at="2025-03-07T00:12:17 IST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.test.SubmitOrderTest_Browser -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2025-03-07T00:12:17 IST" name="ErrorValidationTest" finished-at="2025-03-07T00:12:38 IST" duration-ms="20904">
      <class name="com.test.Error_Validation_Test">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.Error_Validation_Test@4748a0f9]" started-at="2025-03-07T00:12:17 IST" name="launchApplication" finished-at="2025-03-07T00:12:23 IST" duration-ms="5808" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="login_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@4748a0f9]" started-at="2025-03-07T00:12:23 IST" name="login_error_Validation" finished-at="2025-03-07T00:12:24 IST" duration-ms="1136" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.test.Error_Validation_Test.login_error_Validation(Error_Validation_Test.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_error_Validation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.Error_Validation_Test@4748a0f9]" started-at="2025-03-07T00:12:24 IST" name="teardown" finished-at="2025-03-07T00:12:24 IST" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.Error_Validation_Test@4748a0f9]" started-at="2025-03-07T00:12:24 IST" name="launchApplication" finished-at="2025-03-07T00:12:31 IST" duration-ms="6368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="product_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@4748a0f9]" started-at="2025-03-07T00:12:31 IST" name="product_error_Validation" finished-at="2025-03-07T00:12:38 IST" duration-ms="7045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- product_error_Validation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.Error_Validation_Test@4748a0f9]" started-at="2025-03-07T00:12:38 IST" name="teardown" finished-at="2025-03-07T00:12:38 IST" duration-ms="69" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.test.Error_Validation_Test -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- SubmitOrderSuite -->
</testng-results>
